Adding Acknowledgements in README
OAKevin/pet-carev3 pull request #2
Opened 2021-09-14 01:59 UTC by jessikra

We should all add some feedback here

2021-09-14 02:01 UTC, jessikra reviewed
Please add feedback

2021-09-14 02:03 UTC, JJaime1996 reviewed
Hello! Can you see this?

2021-09-15 01:20 UTC, Danny393 commented
Looks good so far

2021-09-15 01:21 UTC, Danny393 commented on README.md
> +<We need to add Project Owner and team info>
Make sure to remember to fill in all the placeholder values near the end of the project

2021-09-15 01:59 UTC, dailenperezFIU commented
Looks good to me :)

2021-09-15 04:19 UTC, OAKevin requested changes
Should we use https://expo.dev/ as the expo website?

2021-09-15 20:53 UTC, rlope265 commented on README.md
>  Your Name - [@your_twitter](https://twitter.com/your_username) - email@example.com
Is this section for everyone in the team to put their contact information?

2021-09-15 23:27 UTC, armand737 commented
It looks great!

2021-10-04 21:33 UTC, OAKevin approved these changes
Ignore my comment I tested it and Its working fine on my laptop

2021-11-30 21:36 UTC, closed without merging